version: "3.5"

services:
  db:
    image: mysql/mysql-server:8.0
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: social_network
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

volumes:
  db_data: {}
